version: 2

project_name: dhg

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/dhg
    binary: dhg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Improvements"
      regexp: '^.*?(perf|refactor)(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^Merge pull request"

dockers:
  - image_templates:
      - "ghcr.io/alexgromer/dhg:{{ .Version }}"
      - "ghcr.io/alexgromer/dhg:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/AlexGromer/deckhouse-helm-generator"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goos: linux
    goarch: amd64

brews:
  - repository:
      owner: AlexGromer
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/AlexGromer/deckhouse-helm-generator"
    description: "CLI tool for generating Helm charts from Kubernetes/Deckhouse resources"
    license: "Apache-2.0"
    test: |
      system "#{bin}/dhg", "version"
    install: |
      bin.install "dhg"

release:
  github:
    owner: AlexGromer
    name: deckhouse-helm-generator
  draft: false
  prerelease: auto
