package helm

import (
	"fmt"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"
)

// ValuesBuilder builds a values.yaml structure.
type ValuesBuilder struct {
	values map[string]interface{}
}

// NewValuesBuilder creates a new values builder.
func NewValuesBuilder() *ValuesBuilder {
	return &ValuesBuilder{
		values: make(map[string]interface{}),
	}
}

// SetGlobal sets global values.
func (b *ValuesBuilder) SetGlobal(key string, value interface{}) *ValuesBuilder {
	if b.values["global"] == nil {
		b.values["global"] = make(map[string]interface{})
	}
	global := b.values["global"].(map[string]interface{})
	global[key] = value
	return b
}

// AddService adds a service with its configuration.
func (b *ValuesBuilder) AddService(name string, config map[string]interface{}) *ValuesBuilder {
	if b.values["services"] == nil {
		b.values["services"] = make(map[string]interface{})
	}
	services := b.values["services"].(map[string]interface{})

	// Ensure service has enabled flag
	if _, ok := config["enabled"]; !ok {
		config["enabled"] = true
	}

	services[name] = config
	return b
}

// SetValue sets a value at a given path (dot-notation).
func (b *ValuesBuilder) SetValue(path string, value interface{}) *ValuesBuilder {
	parts := strings.Split(path, ".")
	current := b.values

	for i, part := range parts {
		if i == len(parts)-1 {
			// Last part - set the value
			current[part] = value
		} else {
			// Intermediate part - ensure it's a map
			if current[part] == nil {
				current[part] = make(map[string]interface{})
			}
			if next, ok := current[part].(map[string]interface{}); ok {
				current = next
			} else {
				// Can't traverse further
				return b
			}
		}
	}

	return b
}

// GetValue gets a value at a given path.
func (b *ValuesBuilder) GetValue(path string) (interface{}, bool) {
	parts := strings.Split(path, ".")
	current := b.values

	for i, part := range parts {
		if i == len(parts)-1 {
			// Last part - get the value
			val, ok := current[part]
			return val, ok
		} else {
			// Intermediate part
			if next, ok := current[part].(map[string]interface{}); ok {
				current = next
			} else {
				return nil, false
			}
		}
	}

	return nil, false
}

// MergeValues merges another values map into this builder.
func (b *ValuesBuilder) MergeValues(values map[string]interface{}) *ValuesBuilder {
	b.values = mergeMaps(b.values, values)
	return b
}

// Build generates the values.yaml content with comments.
func (b *ValuesBuilder) Build() (string, error) {
	// Add default global values if not present
	if b.values["global"] == nil {
		b.SetGlobal("imageRegistry", "")
		b.SetGlobal("imagePullSecrets", []interface{}{})
	}

	// Convert to YAML
	yamlBytes, err := yaml.Marshal(b.values)
	if err != nil {
		return "", fmt.Errorf("failed to marshal values to YAML: %w", err)
	}

	// Add comments
	yamlStr := string(yamlBytes)
	yamlStr = addCommentsToValues(yamlStr)

	return yamlStr, nil
}

// BuildMap returns the values as a map.
func (b *ValuesBuilder) BuildMap() map[string]interface{} {
	return b.values
}

// addCommentsToValues adds helpful comments to the values.yaml output.
func addCommentsToValues(yaml string) string {
	var sb strings.Builder

	sb.WriteString("# Default values for the chart.\n")
	sb.WriteString("# This file was generated by Deckhouse Helm Generator.\n")
	sb.WriteString("# You can override these values during installation:\n")
	sb.WriteString("#   helm install my-release ./chart --values custom-values.yaml\n\n")

	lines := strings.Split(yaml, "\n")
	inGlobal := false
	inServices := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Detect sections
		if strings.HasPrefix(line, "global:") {
			sb.WriteString("# Global settings that apply to all services\n")
			inGlobal = true
			inServices = false
		} else if strings.HasPrefix(line, "services:") {
			if inGlobal {
				sb.WriteString("\n")
			}
			sb.WriteString("# Service-specific configuration\n")
			sb.WriteString("# Each service can be individually enabled/disabled\n")
			inGlobal = false
			inServices = true
		} else if inServices && !strings.HasPrefix(line, " ") && trimmed != "" {
			// New top-level service entry — add blank line separator.
			sb.WriteString("\n")
		}

		sb.WriteString(line)
		sb.WriteString("\n")
	}

	return sb.String()
}

// mergeMaps deeply merges two maps.
func mergeMaps(dst, src map[string]interface{}) map[string]interface{} {
	result := make(map[string]interface{})

	// Copy dst
	for k, v := range dst {
		result[k] = v
	}

	// Merge src
	for k, v := range src {
		if dstVal, ok := result[k]; ok {
			// Both are maps - merge recursively
			if dstMap, dstIsMap := dstVal.(map[string]interface{}); dstIsMap {
				if srcMap, srcIsMap := v.(map[string]interface{}); srcIsMap {
					result[k] = mergeMaps(dstMap, srcMap)
					continue
				}
			}
		}
		// Otherwise, override
		result[k] = v
	}

	return result
}

// FormatValuesForService formats service-specific values.
func FormatValuesForService(serviceName string, values map[string]interface{}) map[string]interface{} {
	formatted := make(map[string]interface{})

	// Ensure enabled flag
	if _, ok := values["enabled"]; !ok {
		formatted["enabled"] = true
	} else {
		formatted["enabled"] = values["enabled"]
	}

	// Sort keys for consistent output
	keys := make([]string, 0, len(values))
	for k := range values {
		if k != "enabled" {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)

	// Add sorted values
	for _, k := range keys {
		formatted[k] = values[k]
	}

	return formatted
}

// GenerateValuesSchema generates a values.schema.json for validation.
func GenerateValuesSchema(services []string) string {
	schema := map[string]interface{}{
		"$schema": "http://json-schema.org/draft-07/schema#",
		"type":    "object",
		"properties": map[string]interface{}{
			"global": map[string]interface{}{
				"type": "object",
				"properties": map[string]interface{}{
					"imageRegistry": map[string]interface{}{
						"type":        "string",
						"description": "Global Docker image registry",
					},
					"imagePullSecrets": map[string]interface{}{
						"type":        "array",
						"description": "Global image pull secrets",
						"items": map[string]interface{}{
							"type": "object",
						},
					},
				},
			},
			"services": map[string]interface{}{
				"type": "object",
				"properties": buildServiceSchemaProperties(services),
			},
		},
	}

	schemaBytes, _ := yaml.Marshal(schema)
	return string(schemaBytes)
}

func buildServiceSchemaProperties(services []string) map[string]interface{} {
	props := make(map[string]interface{})

	for _, svc := range services {
		props[svc] = map[string]interface{}{
			"type": "object",
			"properties": map[string]interface{}{
				"enabled": map[string]interface{}{
					"type":        "boolean",
					"description": fmt.Sprintf("Enable %s service", svc),
				},
			},
		}
	}

	return props
}
