apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: default
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: myapp
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database
    spec:
      containers:
        - name: database
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: myapp
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: default
  labels:
    app.kubernetes.io/name: database
spec:
  selector:
    app.kubernetes.io/name: database
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
