package generator

import (
	"fmt"
	"strings"

	"github.com/deckhouse/deckhouse-helm-generator/pkg/types"
)

// SOPSOptions configures SOPS and helm-secrets integration generation.
type SOPSOptions struct {
	// KeyType is the encryption key type: "age", "pgp", "aws-kms", "gcp-kms".
	KeyType string
	// KeyID is the key identifier (age recipient, PGP fingerprint, KMS ARN, GCP resource ID).
	KeyID string
	// EncryptedFiles lists the files that should be encrypted (used in creation_rules).
	EncryptedFiles []string
	// Provider is the secrets provider: "sops" or "helm-secrets".
	Provider string
}

// GenerateSOPSConfig generates a .sops.yaml configuration and returns a
// map of filename → content. Always returns a non-nil map with a ".sops.yaml" key.
func GenerateSOPSConfig(opts SOPSOptions) map[string]string {
	var sb strings.Builder

	sb.WriteString("# SOPS configuration\n")
	sb.WriteString("# Generated by deckhouse-helm-generator\n")

	// Key-type-specific configuration.
	switch opts.KeyType {
	case "age":
		sb.WriteString("creation_rules:\n")
		if len(opts.EncryptedFiles) > 0 {
			for _, f := range opts.EncryptedFiles {
				sb.WriteString(fmt.Sprintf("  - path_regex: %s\n", f))
				sb.WriteString("    age: >-\n")
				sb.WriteString(fmt.Sprintf("      %s\n", opts.KeyID))
			}
		} else {
			sb.WriteString("  - age: >-\n")
			sb.WriteString(fmt.Sprintf("      %s\n", opts.KeyID))
		}

	case "pgp":
		sb.WriteString("creation_rules:\n")
		if len(opts.EncryptedFiles) > 0 {
			for _, f := range opts.EncryptedFiles {
				sb.WriteString(fmt.Sprintf("  - path_regex: %s\n", f))
				sb.WriteString("    pgp: >-\n")
				sb.WriteString(fmt.Sprintf("      %s\n", opts.KeyID))
			}
		} else {
			sb.WriteString("  - pgp: >-\n")
			sb.WriteString(fmt.Sprintf("      %s\n", opts.KeyID))
		}

	case "aws-kms":
		sb.WriteString("creation_rules:\n")
		if len(opts.EncryptedFiles) > 0 {
			for _, f := range opts.EncryptedFiles {
				sb.WriteString(fmt.Sprintf("  - path_regex: %s\n", f))
				sb.WriteString("    kms: >-\n")
				sb.WriteString(fmt.Sprintf("      %s\n", opts.KeyID))
			}
		} else {
			sb.WriteString("  - kms: >-\n")
			sb.WriteString(fmt.Sprintf("      %s\n", opts.KeyID))
		}

	case "gcp-kms":
		sb.WriteString("creation_rules:\n")
		if len(opts.EncryptedFiles) > 0 {
			for _, f := range opts.EncryptedFiles {
				sb.WriteString(fmt.Sprintf("  - path_regex: %s\n", f))
				sb.WriteString("    gcp_kms: >-\n")
				sb.WriteString(fmt.Sprintf("      %s\n", opts.KeyID))
			}
		} else {
			sb.WriteString("  - gcp_kms: >-\n")
			sb.WriteString(fmt.Sprintf("      %s\n", opts.KeyID))
		}

	default:
		// Empty opts or unknown key type — emit a valid YAML skeleton.
		sb.WriteString("creation_rules: []\n")
	}

	return map[string]string{
		".sops.yaml": sb.String(),
	}
}

// GenerateHelmSecretsWrapper generates a shell wrapper script for helm-secrets or sops.
// The wrapper references the appropriate tool invocation based on opts.Provider.
func GenerateHelmSecretsWrapper(opts SOPSOptions) string {
	var sb strings.Builder

	sb.WriteString("#!/usr/bin/env sh\n")
	sb.WriteString("# Helm secrets wrapper — generated by deckhouse-helm-generator\n")
	sb.WriteString("set -e\n\n")

	switch opts.Provider {
	case "helm-secrets":
		sb.WriteString("# helm-secrets plugin wrapper\n")
		sb.WriteString("# Usage: ./decrypt-secrets.sh <file.yaml>\n\n")
		sb.WriteString("helm secrets decrypt \"$@\"\n")
	default: // "sops" and any other value
		sb.WriteString("# sops wrapper\n")
		sb.WriteString("# Usage: ./decrypt-secrets.sh <file.yaml>\n\n")
		sb.WriteString("sops --decrypt \"$@\"\n")
	}

	if opts.KeyType == "age" && opts.KeyID != "" {
		sb.WriteString(fmt.Sprintf("\n# Age recipient: %s\n", opts.KeyID))
	}

	return sb.String()
}

// InjectSOPS injects SOPS configuration files into a chart's ExternalFiles.
// Returns the updated chart (copy-on-write) and the count of files added.
// Returns (nil, 0) if chart is nil.
func InjectSOPS(chart *types.GeneratedChart, opts SOPSOptions) (*types.GeneratedChart, int) {
	if chart == nil {
		return nil, 0
	}

	// Build existing-paths set for idempotency.
	existing := make(map[string]bool, len(chart.ExternalFiles))
	for _, ef := range chart.ExternalFiles {
		existing[ef.Path] = true
	}

	// Copy ExternalFiles slice (copy-on-write).
	newFiles := make([]types.ExternalFileInfo, len(chart.ExternalFiles))
	copy(newFiles, chart.ExternalFiles)

	count := 0

	// Add .sops.yaml.
	sopsConfig := GenerateSOPSConfig(opts)
	for path, content := range sopsConfig {
		if existing[path] {
			continue
		}
		newFiles = append(newFiles, types.ExternalFileInfo{
			Path:    path,
			Content: content,
		})
		count++
	}

	// Add helm-secrets wrapper if provider is set.
	if opts.Provider != "" {
		wrapperPath := "scripts/decrypt-secrets.sh"
		if !existing[wrapperPath] {
			wrapper := GenerateHelmSecretsWrapper(opts)
			newFiles = append(newFiles, types.ExternalFileInfo{
				Path:    wrapperPath,
				Content: wrapper,
			})
			count++
		}
	}

	result := copyChartTemplates(chart)
	result.ExternalFiles = newFiles
	return result, count
}
