package generator

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/deckhouse/deckhouse-helm-generator/pkg/types"
)

// HashiCorp Vault Agent injection (feature "vault-agent").
//
// Every Deployment, StatefulSet and DaemonSet that consumes Secrets gets the
// Vault Agent injector annotations for those Secrets: the agent renders
// <path-prefix>/<secret> to /vault/secrets/<secret> (as KEY=value lines with
// format=env). The annotations are computed at render time from the
// vaultAgent values block, so the role, paths and the whole injection can be
// changed per environment.

// vaultAgentPodAnnotationsHook is the pod-annotations block of the generated
// Deployment/StatefulSet/DaemonSet templates that the feature extends.
const vaultAgentPodAnnotationsHook = "{{- with .podAnnotations }}"

// vaultAgentWorkloadKinds are the kinds whose generated templates carry the
// pod-annotations hook.
var vaultAgentWorkloadKinds = map[string]bool{"Deployment": true, "StatefulSet": true, "DaemonSet": true}

func applyVaultAgentFeature(chart *types.GeneratedChart, fc FeatureContext) (*types.GeneratedChart, error) {
	kv, err := strconv.Atoi(fc.Param("kv-version"))
	if err != nil || (kv != 1 && kv != 2) {
		return nil, fmt.Errorf("kv-version must be 1 or 2, got %q", fc.Param("kv-version"))
	}
	format := fc.Param("format")
	if format != "env" && format != "raw" {
		return nil, fmt.Errorf("format must be env or raw, got %q", format)
	}
	if fc.Param("path-prefix") == "" {
		return nil, fmt.Errorf("path-prefix must not be empty")
	}

	// Named templates are global across an umbrella chart and its subcharts
	// (and library-mode wrappers share the library prefix): key it by chart.
	define := chart.Name + ".vaultAgent.podAnnotations"

	out := cloneChart(chart)
	patched := 0
	for _, w := range secChartWorkloads(chart, fc.Graph) {
		if !vaultAgentWorkloadKinds[w.kind] {
			continue
		}
		refs := secSecretRefs(w.podSpec)
		if len(refs) == 0 {
			continue
		}
		path := w.res.TemplatePath
		content := out.Templates[path]
		if strings.Count(content, vaultAgentPodAnnotationsHook) != 1 {
			continue // template does not have the expected shape; leave it alone
		}
		names := make([]string, 0, len(refs))
		for _, r := range refs {
			names = append(names, fmt.Sprintf("%q", r.Name))
		}
		replacement := fmt.Sprintf(`{{- with include %q (dict "root" $ "podAnnotations" .podAnnotations "secrets" (list %s)) | fromYaml }}`,
			define, strings.Join(names, " "))
		out.Templates[path] = strings.Replace(content, vaultAgentPodAnnotationsHook, replacement, 1)
		patched++
	}
	if patched == 0 {
		return chart, nil
	}

	role := fc.Param("role")
	if role == "" {
		role = chart.Name
	}
	if err := secAddValues(out, "vaultAgent",
		"# HashiCorp Vault Agent injection (dhg feature: vault-agent).\n"+
			"# Workloads using a Secret <name> get it from <secretPathPrefix>/<name>\n"+
			"# rendered to /vault/secrets/<name> (secretFormat env: KEY=value lines).\n",
		map[string]interface{}{
			"enabled":          true,
			"role":             role,
			"authPath":         fc.Param("auth-path"),
			"secretPathPrefix": fc.Param("path-prefix"),
			"kvVersion":        kv,
			"secretFormat":     format,
			"prePopulateOnly":  fc.BoolParam("pre-populate-only"),
			"extraAnnotations": map[string]interface{}{},
		}); err != nil {
		return nil, err
	}
	tplPath := "templates/_vault-agent.tpl"
	if err := secAddTemplate(out, tplPath, vaultAgentHelperTemplate(define)); err != nil {
		return nil, err
	}
	return out, nil
}

// vaultAgentHelperTemplate renders the named template that merges the Vault
// Agent annotations with the workload's own pod annotations (the latter win).
func vaultAgentHelperTemplate(define string) string {
	return `{{- /* Generated by dhg feature "vault-agent". Requires the Vault Agent injector. */}}
{{- define "` + define + `" -}}
{{- $annotations := dict -}}
{{- $va := .root.Values.vaultAgent -}}
{{- if and $va $va.enabled -}}
{{- $_ := set $annotations "vault.hashicorp.com/agent-inject" "true" -}}
{{- $_ := set $annotations "vault.hashicorp.com/role" (toString $va.role) -}}
{{- with $va.authPath }}{{ $_ := set $annotations "vault.hashicorp.com/auth-path" (toString .) }}{{ end -}}
{{- if $va.prePopulateOnly }}{{ $_ := set $annotations "vault.hashicorp.com/agent-pre-populate-only" "true" }}{{ end -}}
{{- $data := ternary ".Data.data" ".Data" (eq (int ($va.kvVersion | default 2)) 2) -}}
{{- range .secrets -}}
{{- $path := printf "%s/%s" (trimSuffix "/" (toString $va.secretPathPrefix)) . -}}
{{- $_ := set $annotations (printf "vault.hashicorp.com/agent-inject-secret-%s" .) $path -}}
{{- if eq (toString $va.secretFormat) "env" -}}
{{- $_ := set $annotations (printf "vault.hashicorp.com/agent-inject-template-%s" .) (printf "{{- with secret %q -}}\n{{- range $k, $v := %s }}\n{{ $k }}={{ $v }}\n{{- end }}\n{{- end }}\n" $path $data) -}}
{{- end -}}
{{- end -}}
{{- with $va.extraAnnotations }}{{ $annotations = mergeOverwrite $annotations . }}{{ end -}}
{{- end -}}
{{- with .podAnnotations }}{{ $annotations = mergeOverwrite $annotations . }}{{ end -}}
{{- toYaml $annotations -}}
{{- end -}}
`
}
