apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-backup
  namespace: default
  labels:
    app.kubernetes.io/name: backup
spec:
  schedule: "0 2 * * *"
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: backup
              image: backup-tool:1.0
              command: ["/backup.sh"]
              env:
                - name: BACKUP_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: backup-config
                      key: bucket
              resources:
                requests:
                  cpu: "200m"
                  memory: "256Mi"
                limits:
                  cpu: "1"
                  memory: "512Mi"
          restartPolicy: OnFailure
