apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: default
  labels:
    app.kubernetes.io/name: migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  completions: 1
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: migrate
          image: migration-tool:2.0
          command: ["./migrate", "up"]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: host
      restartPolicy: Never
